import turtle
flag = turtle.Turtle()
turtle.bgcolor("white")
flag.speed("slow")
flag.begin_fill()
flag.fillcolor('green')
flag.penup()
flag.pendown()
flag.right(90)
flag.forward(300)
flag.left(90)
flag.forward(100)
flag.left(90)
flag.forward(300)
flag.left(90)
flag.forward(100)
flag.end_fill()

flag.back(100)
flag.right(180)
flag.forward(100)
flag.right(90)
flag.forward(300)
flag.right(90)
flag.forward(100)
flag.back(100)
flag.left(180)

flag.begin_fill()
flag.fillcolor("green")
flag.forward(100)
flag.left(90)
flag.forward(300)
flag.left(90)
flag.forward(100)
flag.end_fill()

turtle.mainloop()
