import turtle
turtle.bgcolor("violet")
turtle.pencolor("black")
turtle.speed("fastest")
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.circle(75)
turtle.goto(0, -50)
turtle.right(30)
turtle.forward(100)
turtle.backward(100)
turtle.right(120)
turtle.forward(100)
turtle.backward(100)
turtle.left(60)
turtle.forward(150)
turtle.right(30)
turtle.forward(100)
turtle.backward(100)
turtle.left(60)
turtle.forward(100)

turtle.mainloop()